apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
  namespace: smartcity
  labels:
    app: keycloak
    component: auth
    environment: development
  annotations:
    description: "Persistent storage for Keycloak data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
