apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: smartcity
  labels:
    app: mongodb
    component: database
    environment: development
  annotations:
    description: "Persistent storage for MongoDB data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
