apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: smartcity
  labels:
    app: n8n
    component: automation
    environment: development
  annotations:
    description: "Persistent storage for n8n workflow data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
