apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: smartcity
  labels:
    app: postgres
    component: database
    environment: development
  annotations:
    description: "Persistent storage for PostgreSQL data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
