# Dev-only secret for RabbitMQ credentials
# NÃO COMITAR credenciais de produção neste arquivo.
# Use este secret apenas para ambientes de desenvolvimento/local (Minikube).
# Para regenerar localmente: kubectl create secret generic rabbitmq-secrets \
#   --from-literal=RABBITMQ_DEFAULT_USER=guest \
#   --from-literal=RABBITMQ_DEFAULT_PASS=guest -n <namespace>
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
