apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
  annotations:
    description: "Persistent storage for RabbitMQ data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
