apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: smartcity
  labels:
    app: redis
    component: cache
    environment: development
  annotations:
    description: "Persistent storage for Redis data in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
