# Versão da API do Kubernetes utilizada para este recurso
apiVersion: v1
# Tipo de recurso Kubernetes - Service para exposição de pods
kind: Service
# Metadados que definem as características do service
metadata:
  # Nome único do service no namespace
  name: mongodb-service
  # Namespace onde o service será criado
  namespace: smartcity
  # Labels para identificação e seleção do service
  labels:
    app: mongodb
    component: database
    environment: development
  # Annotations para informações adicionais
  annotations:
    description: "Service to expose MongoDB database for Smart City application"
# Especificações do service
spec:
  # Tipo de service - ClusterIP para acesso interno no cluster
  type: ClusterIP
  # Seletor para identificar os pods que este service deve expor
  selector:
    app: mongodb
    component: database
  # Portas que o service irá expor
  ports:
    # Porta principal do MongoDB
    - name: mongodb
      # Porta do service (onde outros pods se conectam)
      port: 27017
      # Porta do container de destino
      targetPort: 27017
      # Protocolo de comunicação
      protocol: TCP