# Versão da API do Kubernetes utilizada para este recurso
apiVersion: apps/v1
kind: Deployment
metadata:
  # Nome do deployment
  name: redis
  # Namespace onde será criado
  namespace: smartcity
  # Labels para seleção e organização
  labels:
    app: redis
  # Annotations para informações adicionais
  annotations:
    description: "Redis deployment for Smart City application"
spec:
  # Número de réplicas
  replicas: 1
  # Selector para identificar os pods do deployment
  selector:
    matchLabels:
      app: redis
  # Template do pod
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          # Imagem oficial do Redis (versão leve alpine)
          image: redis:7
          # Porta exposta pelo container
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          # Montagens de volume
          volumeMounts:
            - name: redis-data
              mountPath: /data
          # Readiness probe para verificar se o Redis responde ao PING
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          # Liveness probe para verificar a saúde do container
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 30
          # Recursos solicitados e limites para o container Redis
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      # Volumes declarados no pod
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
