version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"         # Porta padrão do RabbitMQ para conexão com clientes
      - "15672:15672"       # Porta para o plugin de gerenciamento (interface web)
    environment:
      RABBITMQ_DEFAULT_USER: guest   # Usuário padrão
      RABBITMQ_DEFAULT_PASS: guest   # Senha padrão
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistência de dados
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "6379:6379"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - app_network

# Volumes
volumes:
  rabbitmq_data: {}
  mongo_data: {}
  redis_data: {}
  portainer_data: {}

# Redes
networks:
  app_network:
    driver: bridge
