apiVersion: v1
kind: ConfigMap
metadata:
  name: house-control-config
data:
  application.yml: |-
    spring:
      application:
        name: house-control
    management:
      endpoints:
        web:
          exposure:
            include: health,info
    logging:
      level:
        root: INFO
  redis:
    host: redis
    port: "6379"
  postgres:
    host: postgres
    port: "5432"
    database: smartcity
