apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-control
  labels:
    app: house-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-control
  template:
    metadata:
      labels:
        app: house-control
    spec:
      containers:
        - name: house-control
          image: ghcr.io/alessandrorsseixas/house-control:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: house-control-secrets
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: house-control-secrets
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: house-control-secrets
                  key: spring.datasource.password
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: house-control-secrets
                  key: redis.host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: house-control-secrets
                  key: redis.port
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
