apiVersion: v1
kind: Service
metadata:
  name: house-control
  labels:
    app: house-control
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: house-control
