apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-deployment
  namespace: smartcity
  labels:
    app: mcp-server
    component: mcp
    environment: development
  annotations:
    description: "MCP Server - integra o cluster e fornece informações em linguagem natural"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
      component: mcp
  template:
    metadata:
      labels:
        app: mcp-server
        component: mcp
        environment: development
    spec:
      containers:
        - name: mcp-server
          image: ghcr.io/smart-city/mcp-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MCP_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: mcp-server-config
                  key: MCP_LOG_LEVEL
            - name: MCP_PROMPT_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  name: mcp-server-config
                  key: MCP_PROMPT_TEMPLATE
            - name: MCP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mcp-server-secrets
                  key: MCP_API_KEY
            - name: CLUSTER_NAMESPACE
              value: "smartcity"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
