apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-pvc
  namespace: smartcity
  labels:
    app: mcp-server
    component: mcp
    environment: development
  annotations:
    description: "PVC para armazenamento local do MCP (cache, embeddings, etc)"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: standard
