apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  namespace: smartcity
  labels:
    app: mcp-server
    component: mcp
    environment: development
  annotations:
    description: "Service exposing MCP Server"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: mcp-server
    component: mcp
