server:
  port: 8081

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8080/realms/smartcity/protocol/openid-connect/certs}

smartcity:
  messaging:
    queues:
      house-commands: house.commands.q

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

micrometer:
  prometheus:
    enabled: true
