apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: smartcity
  labels:
    app: keycloak
    component: auth
    environment: development
spec:
  type: ClusterIP
  selector:
    app: keycloak
    component: auth
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
