apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mcp-server
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MCP_LOG_LEVEL
              value: "debug"
            - name: MCP_PROMPT_TEMPLATE
              valueFrom:
                configMapKeyRef:
                  name: mcp-server-config
                  key: MCP_PROMPT_TEMPLATE
