apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  template:
    spec:
      containers:
        - name: keycloak
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: KEYCLOAK_LOGLEVEL
              value: "DEBUG"
