apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/mongo
  - mongodb-secret.yaml
patches:
- target:
    kind: StatefulSet
    name: mongodb-statefulset
  path: deployment-patch.yaml
