apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: smartcity
  labels:
    app: n8n
    component: workflow
    environment: development
  annotations:
    description: "PVC para persistência de dados do n8n (usuário: /home/node/.n8n)"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: standard
