apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: smartcity
  labels:
    app: n8n
    component: workflow
    environment: development
  annotations:
    description: "ClusterIP Service exposing n8n UI and API"
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: n8n
    component: workflow
