apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
data:
  enabled_plugins: |
    [rabbitmq_management].
  rabbitmq.conf: |
    loopback_users.guest = false
    default_user = admin
    default_pass = rabbitmq123
    management.listener.port = 15672
    listeners.tcp.default = 5672
