apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-deployment
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
  annotations:
    description: "RabbitMQ deployment for Smart City"
spec:
  serviceName: rabbitmq-service
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      component: messaging
  template:
    metadata:
      labels:
        app: rabbitmq
        component: messaging
        environment: development
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
    volumes: []
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        # storageClassName: standard
