# Service para expor RabbitMQ dentro do namespace
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
  annotations:
    description: "Service to expose RabbitMQ"
spec:
  # Tipo ClusterIP para exposição interna
  type: ClusterIP
  selector:
    app: rabbitmq
    component: messaging
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
