apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-angular
  namespace: argocd
spec:
  project: iot
  source:
    repoURL: 'https://github.com/alessandrorsseixas/smart-city-org'
    targetRevision: HEAD
    path: k8s/overlays/dev/frontend-angular
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: smartcity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
