apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base/house-control

resources:
  - secret-dev.yaml

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
