apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-control-service
  namespace: smart-city
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-control-service
  template:
    metadata:
      labels:
        app: house-control-service
    spec:
      containers:
      - name: house-control-service
        image: smartcity/house-control-service:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Server=mysql-service;Database=SmartCityHouseControl;User=root;Password=smartcity123;"
        - name: ConnectionStrings__Redis
          value: "redis-service:6379"
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret-key
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: house-control-service
  namespace: smart-city
spec:
  selector:
    app: house-control-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP