name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:

jobs:
  lint-and-validate:
    name: Lint shell scripts & validate kustomize
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck curl

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: ShellCheck for scripts
        run: |
          echo "Running shellcheck on scripts/dev/*.sh"
          shellcheck -x scripts/dev/*.sh || true

      - name: Kustomize build (validate overlays)
        run: |
          echo "Validating kustomize overlays"
          # kubectl kustomize will exit non-zero if kustomize fails
          kubectl kustomize k8s/overlays/dev > /dev/null

      - name: List changed files (for debugging)
        run: git status --porcelain; git rev-parse --abbrev-ref HEAD
